### ISSUE TITLE
Reg: Recording Error and Grafana setup

### ISSUE THREAD

**Issue by naveenbabusa** [switnet-ltd/quick-jibri-installer#10]
Hi Team 

Firstly thanks for putting this together. It really helped me to set up at one shot all the servers. I am stuck at one place while starting the recording . Not sure what changes in config i need to make . Can you guide me . It looks like Jibri is not accessible 

Here is the Log from JVB any guidance. 

MucClient.lambda$getConnectAndLoginCallable$8#669: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: ‘localhost:5222’ failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connec$
at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$8(MucClient.java:664)
at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2020-08-14 09:50:01.207 INFO: [20] TaskPools.#81: TaskPools detected 4 processors, creating the CPU pool with that many threads
2020-08-14 09:50:01.209 INFO: [20] Videobridge.createConference#255: create_conf, id=eae7d8f2c386f378 gid=-1 logging=false
2020-08-14 09:50:01.279 WARNING: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$8#669: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: ‘localhost:5222’ failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connec$
at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$8(MucClient.java:664)
at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by Ark74** [comment]
Are you using a FQDN?
Our installer script takes care of the whole installation, no need to make changes.
I can't help you with this log, I need the steps to reproduce the error, please take the time to fill a complete report so we can help.

In case you require custom paid support, please contact us at https://switnet.net/support/
Regards

**Comment by Ark74** [comment]
@naveenbabusa Please share the content of qj-installer.log
That might be of better use.

**Comment by Ark74** [comment]
Answered on #11
