### ISSUE TITLE
Call recording does not work with jwt auth

### ISSUE THREAD

**Issue by AhmadjoniMuhamad** [switnet-ltd/quick-jibri-installer#47]
After installing jitsi with jwt, everything works correctly except for recording video calls. There are no errors in the console, I did not find it in other logs either. There are several lines in the jicofo logs where it says that the user cannot be authorized. Maybe due to the fact that my authorization goes through jwt and the rest of the access is closed for this, the user by recording cannot start recording?

`
Last login: Sun May  2 20:21:30 2021 from 192.168.2.1
caritas@ubuntu2:~$ sudo su
[sudo] password for caritas:
root@ubuntu2:/home/caritas# tail -f /var/log/jitsi/jicofo.log
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Schedule                                                                                          dThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThread                                                                                          PoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Jicofo 2021-05-02 20:34:59.843 INFO: [47] [room=test@conference.conf.farogir.tj] JibriRecorder.publ                                                                                          ishJibriRecordingStatus#244: Got jibri status off and failure error
Jicofo 2021-05-02 20:34:59.843 INFO: [47] [room=test@conference.conf.farogir.tj] JibriRecorder.publ                                                                                          ishJibriRecordingStatus#276: Publishing new jibri-recording-status: <jibri-recording-status xmlns='                                                                                          http://jitsi.org/protocol/jibri' status='off' failure_reason='error' session_id='rixvlycrvowrkmsc'                                                                                           recording_mode='file'/> in: test@conference.conf.farogir.tj
Jicofo 2021-05-02 20:34:59.844 INFO: [47] JibriSession.cleanupSession#413: Cleaning up current Jibr                                                                                          iSession
Jicofo 2021-05-02 20:36:45.936 INFO: [29] JibriSession.startInternal#335: Starting session with Jib                                                                                          ri jibribrewery@internal.auth.conf.farogir.tj/Live
Jicofo 2021-05-02 20:36:45.936 INFO: [29] JibriSession.sendJibriStartIq#497: Starting Jibri jibribr                                                                                          ewery@internal.auth.conf.farogir.tj/Live for stream ID: null in room: test@conference.conf.farogir.                                                                                          tj
Jicofo 2021-05-02 20:36:46.261 INFO: [29] JibriSession.processJibriIqFromJibri#458: Updating status                                                                                           from JIBRI: <iq to='focus@auth.conf.farogir.tj/focus' from='jibribrewery@internal.auth.conf.farogi                                                                                          r.tj/Live' id='hU3ck-202' type='result'><jibri xmlns='http://jitsi.org/protocol/jibri' status='pend                                                                                          ing'/></iq> for test@conference.conf.farogir.tj
Jicofo 2021-05-02 20:36:46.261 INFO: [29] JibriSession.handleJibriStatusUpdate#629: Got Jibri statu                                                                                          s update: Jibri jibribrewery@internal.auth.conf.farogir.tj/Live has status pending and failure reas                                                                                          on null, current Jibri jid is jibribrewery@internal.auth.conf.farogir.tj/Live
Jicofo 2021-05-02 20:36:46.262 INFO: [29] [room=test@conference.conf.farogir.tj] JibriRecorder.hand                                                                                          leStartRequest#163: Started Jibri session
Jicofo 2021-05-02 20:37:17.752 INFO: [47] JibriSession.processJibriIqFromJibri#458: Updating status                                                                                           from JIBRI: <iq to='focus@auth.conf.farogir.tj/focus' from='jibribrewery@internal.auth.conf.farogi                                                                                          r.tj/Live' id='Zm9jdXNAYXV0aC5jb25mLmZhcm9naXIudGovZm9jdXMAdXh2MkUtNDAAUhZRspbpyajuevdbkyDKuw==' ty                                                                                          pe='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_                                                                                          retry='true'/></iq> for test@conference.conf.farogir.tj
Jicofo 2021-05-02 20:37:17.753 INFO: [47] JibriSession.handleJibriStatusUpdate#629: Got Jibri statu                                                                                          s update: Jibri jibribrewery@internal.auth.conf.farogir.tj/Live has status off and failure reason e                                                                                          rror, current Jibri jid is jibribrewery@internal.auth.conf.farogir.tj/Live
Jicofo 2021-05-02 20:37:17.753 INFO: [47] JibriSession.handleJibriStatusUpdate#648: Jibri is no lon                                                                                          ger pending, cancelling pending timeout task
Jicofo 2021-05-02 20:37:17.753 INFO: [47] JibriSession.handleJibriStatusUpdate#669: Jibri failed, t                                                                                          rying to fall back to another Jibri
Jicofo 2021-05-02 20:37:17.754 SEVERE: [47] JibriSession.startInternal#324: Unable to find an avail                                                                                          able Jibri, can't start
Jicofo 2021-05-02 20:37:17.754 WARNING: [47] JibriSession.handleJibriStatusUpdate#680: Failed to fa                                                                                          ll back to another Jibri, this session has now failed: org.jitsi.jicofo.jibri.JibriSession$StartExc                                                                                          eption$AllBusy: All jibri instances are busy
org.jitsi.jicofo.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
        at org.jitsi.jicofo.jibri.JibriSession.startInternal(JibriSession.java:327)
        at org.jitsi.jicofo.jibri.JibriSession.start(JibriSession.java:303)
        at org.jitsi.jicofo.jibri.JibriSession.retryRequestWithAnotherJibri(JibriSession.java:605)
        at org.jitsi.jicofo.jibri.JibriSession.handleJibriStatusUpdate(JibriSession.java:673)
        at org.jitsi.jicofo.jibri.JibriSession.processJibriIqFromJibri(JibriSession.java:460)
        at org.jitsi.jicofo.jibri.JibriSession.processJibriIqRequestFromJibri(JibriSession.java:444                                                                                          )
        at org.jitsi.jicofo.jibri.BaseJibri.doHandleIQRequest(BaseJibri.java:257)
        at org.jitsi.jicofo.jibri.BaseJibri.lambda$new$0(BaseJibri.java:117)
        at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:325)
        at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:133)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Schedule                                                                                          dThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThread                                                                                          PoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Jicofo 2021-05-02 20:37:17.755 INFO: [47] [room=test@conference.conf.farogir.tj] JibriRecorder.publ                                                                                          ishJibriRecordingStatus#244: Got jibri status off and failure error
Jicofo 2021-05-02 20:37:17.755 INFO: [47] [room=test@conference.conf.farogir.tj] JibriRecorder.publ                                                                                          ishJibriRecordingStatus#276: Publishing new jibri-recording-status: <jibri-recording-status xmlns='                                                                                          http://jitsi.org/protocol/jibri' status='off' failure_reason='error' session_id='xkyvaninwfwvzzzk'                                                                                           recording_mode='file'/> in: test@conference.conf.farogir.tj
Jicofo 2021-05-02 20:37:17.756 INFO: [47] JibriSession.cleanupSession#413: Cleaning up current Jibr                                                                                          iSession
`

**Comment by Ark74** [comment]
Please try  the latest release, we have fixed this issue on #48 
Testing and feedback is welcome.

**Comment by Ark74** [comment]
Please reopen if the issue persist.
